### ISSUE TITLE
 Failed to exec build script

### ISSUE THREAD

**Issue by lazy1523** [dfinity/internet-identity#390]
i try run` II_ENV=development dfx deploy --no-wallet --argument '(null)']`
but is error

**Comment by lazy1523** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle internet_identity_assets@0.1.0~prebuild: internet_identity_assets@0.1.0
6 info lifecycle internet_identity_assets@0.1.0~build: internet_identity_assets@0.1.0
7 verbose lifecycle internet_identity_assets@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle internet_identity_assets@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/panhy/Documents/dfinity/Demo/internet-identity/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle internet_identity_assets@0.1.0~build: CWD: /Users/panhy/Documents/dfinity/Demo/internet-identity
10 silly lifecycle internet_identity_assets@0.1.0~build: Args: [ '-c', 'NODE_ENV=production webpack' ]
11 silly lifecycle internet_identity_assets@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle internet_identity_assets@0.1.0~build: Failed to exec build script
13 verbose stack Error: internet_identity_assets@0.1.0 build: `NODE_ENV=production webpack`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid internet_identity_assets@0.1.0
15 verbose cwd /Users/panhy/Documents/dfinity/Demo/internet-identity
16 verbose Darwin 20.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error internet_identity_assets@0.1.0 build: `NODE_ENV=production webpack`
22 error Exit status 1
23 error Failed at the internet_identity_assets@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by lazy1523** [comment]
pls help me

**Comment by nmattia** [comment]
Hi, can you run `npm run build` and copy the output here? What versions of dfx and npm are you using?

**Comment by aterga** [comment]
Closing — the build tooling has changed completely since 2021 (dfx, Node, build system). For current build instructions, see the project README.
