### ISSUE TITLE
secp256k1 unavailable, reverting to browser version

### ISSUE THREAD

**Issue by ralyodio** [dfinity/internet-identity#606]
The error is unclear where its coming from but I get this error:

```
secp256k1 unavailable, reverting to browser version
8:43:38 AM [vite] Error when evaluating SSR module /node_modules/@dfinity/identity/node_modules/tweetnacl/nacl-fast.js?v=7d3a1fc0:
ReferenceError: self is not defined
    at /node_modules/@dfinity/identity/node_modules/tweetnacl/nacl-fast.js?v=7d3a1fc0:2391:72
    at instantiateModule (/home/ettinger/src/oblivion/Catalyze-frontend/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:15)
8:43:38 AM [vite] Error when evaluating SSR module /node_modules/@dfinity/identity/lib/esm/identity/ed25519.js:
ReferenceError: self is not defined
    at /node_modules/@dfinity/identity/node_modules/tweetnacl/nacl-fast.js?v=7d3a1fc0:2391:72
    at instantiateModule (/home/ettinger/src/oblivion/Catalyze-frontend/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:15)
8:43:38 AM [vite] Error when evaluating SSR module /node_modules/@dfinity/identity/lib/esm/index.js?v=7d3a1fc0:
ReferenceError: self is not defined
    at /node_modules/@dfinity/identity/node_modules/tweetnacl/nacl-fast.js?v=7d3a1fc0:2391:72
    at instantiateModule (/home/ettinger/src/oblivion/Catalyze-frontend/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:15)
8:43:38 AM [vite] Error when evaluating SSR module /src/lib/auth/openLogin.ts:
ReferenceError: self is not defined
    at /node_modules/@dfinity/identity/node_modules/tweetnacl/nacl-fast.js?v=7d3a1fc0:2391:72
    at instantiateModule (/home/ettinger/src/oblivion/Catalyze-frontend/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:15)
8:43:38 AM [vite] Error when evaluating SSR module /src/lib/chat.ts:
ReferenceError: self is not defined
    at /node_modules/@dfinity/identity/node_modules/tweetnacl/nacl-fast.js?v=7d3a1fc0:2391:72
    at instantiateModule (/home/ettinger/src/oblivion/Catalyze-frontend/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:15)
8:43:38 AM [vite] Error when evaluating SSR module /src/components/Messages/Test.svelte:
ReferenceError: self is not defined
    at /node_modules/@dfinity/identity/node_modules/tweetnacl/nacl-fast.js?v=7d3a1fc0:2391:72
    at instantiateModule (/home/ettinger/src/oblivion/Catalyze-frontend/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:15)
8:43:38 AM [vite] Error when evaluating SSR module /src/routes/messages.svelte:
ReferenceError: self is not defined
    at /node_modules/@dfinity/identity/node_modules/tweetnacl/nacl-fast.js?v=7d3a1fc0:2391:72
    at instantiateModule (/home/ettinger/src/oblivion/Catalyze-frontend/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:15)
self is not defined
ReferenceError: self is not defined
    at /node_modules/@dfinity/identity/node_modules/tweetnacl/nacl-fast.js?v=7d3a1fc0:2391:72
    at instantiateModule (/home/ettinger/src/oblivion/Catalyze-frontend/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:15)
```

I think its coming from here: `import { Ed25519KeyIdentity } from '@dfinity/identity';`

**Comment by nmattia** [comment]
hi @ralyodio , can you clarify how you get this? is this a build error, and if so what command are you running and what environment (npm, node versions, OS, etc) are you running this in?

**Comment by aterga** [comment]
Closing — this was a bug in the `@dfinity/identity` NPM package (not this repo) related to Vite SSR and the `self` global. That package has been updated many times since. Issues with it should be directed to the agent-js repo.
